 ### Problem 4

In [88]:
# import required libraries
import sqlite3
import pandas as pd
from IPython.display import display

# set display options
pd.options.display.max_columns = 100 
pd.set_option("display.max_columns", None) 


# initiate a connection 
sql_conn = sqlite3.connect('test.db')

# prepare the query 
query = 'select * from Garfield;'

# declare & execute a cursor
crsr = sql_conn.cursor() 
crsr.execute(query)

# fetch all records and save it in a dataframe 
dft=pd.read_sql_query(query,sql_conn)

# checking rows n columns of dataframe 
dft_lst = dft.shape
dft_lst
dft.head(10)

,index,8AM,9AM,10AM,11AM,Noon,1PM,2PM,3PM,4PM,5PM,Commute,DayOfWeek,WatchTV,New Field
0,0,Coffee,3,0,9,Sandwich,9,8,6,Tea,0,Long,Mon,Yes,Blah
1,1,Doughnut,8,3,5,Lenthils,10,0,10,PingPong,7,Short,Tue,No,Blah
2,2,Coffee,3,1,2,Taco,5,9,2,PingPong,9,Short,Wed,No,Blah
3,3,Coffee,8,0,9,Sandwich,1,10,0,PingPong,4,Short,Thu,Yes,Blah
4,4,Doughnut,7,10,10,Sandwich,7,0,5,Tea,0,Long,Fri,Yes,Blah
5,5,Sandwich,9,5,7,Lenthils,7,1,7,Coffee,10,Short,Sat,No,Blah
6,6,Doughnut,7,1,4,Lenthils,8,10,7,Coffee,2,Short,Mon,No,Blah
7,7,Coffee,7,7,5,Taco,6,0,8,Tea,8,Short,Tue,No,Blah
8,8,Sandwich,9,2,10,Lenthils,2,7,4,PingPong,8,Short,Wed,No,Blah
9,9,Coffee,7,0,5,Taco,5,9,0,Workout,8,Short,Thu,Yes,Blah

In [106]:
# drop index column from dft
dft=dft.drop(['index'], axis=1)

#--- Above we have imported  Garfield table from test DB into a dataframe called dft
#--- Below we will import the XLS info to the dataframe dfx

In [107]:
# import Garfield Data from XL into a dataframe called dfx
dfx = pd.read_excel ('garfield_activity.xlsx')

# checking rows n columns of dataframe 
dfx_lst=dfx.shape 

dfx.head(10)

,8AM,9AM,10AM,11AM,Noon,1PM,2PM,3PM,4PM,5PM,Commute,DayOfWeek,WatchTV
0,Coffee,5,0,8,Sandwich,6,9,2,Tea,2,Long,Mon,Yes
1,Doughnut,0,6,2,Lenthils,10,0,1,PingPong,7,Short,Tue,No
2,Coffee,3,7,10,Taco,8,4,6,PingPong,2,Short,Wed,No
3,Coffee,1,7,3,Sandwich,7,7,8,PingPong,3,Short,Thu,Yes
4,Doughnut,5,0,2,Sandwich,5,6,9,Tea,3,Long,Fri,Yes
5,Sandwich,8,8,8,Lenthils,3,10,10,Coffee,0,Short,Sat,No
6,Doughnut,7,8,1,Lenthils,6,6,4,Coffee,9,Short,Mon,No
7,Coffee,7,7,2,Taco,10,7,10,Tea,8,Short,Tue,No
8,Sandwich,2,2,8,Lenthils,8,8,0,PingPong,10,Short,Wed,No
9,Coffee,6,9,1,Taco,8,8,4,Workout,4,Short,Thu,Yes

In [108]:
# function to Find rows which are different between two DataFrames.
def dataframe_difference(src_df, tgt_df, which=None):
    
    # Casting the data types of both the dataframe before comparision
    src_df = src_df.applymap(lambda x: x.strip() if type(x) == str else x)
    tgt_df = tgt_df.applymap(lambda x: x.strip() if type(x) == str else x)

    # left df is source af and right df is target df
    comparison_df = src_df.merge(tgt_df, indicator=True, how='outer')
    if which is None:
        diff_df = comparison_df[comparison_df['_merge'] != 'both']
    else:
        diff_df = comparison_df[comparison_df['_merge'] == which]

    return diff_df

In [109]:
# identifying if there are more rows/columns in any of the dataframes
if dfx_lst != dft_lst:
    print('rows/columns are different between the two')
else:
    print('same number of rows/columns are present')

rows/columns are different between the two

In [110]:
# find out which columns are different 
colt = dft.columns.to_list()
colx = dfx.columns.to_list()
for i in range(len(colx)):
    if (dft[colt[i]].dtypes != dfx[colx[i]].dtypes):
        print(colt[i], colx[i])

In [111]:
# rows present only in XL
result = dataframe_difference(dfx,dft,'left_only')
display(result)

,8AM,9AM,10AM,11AM,Noon,1PM,2PM,3PM,4PM,5PM,Commute,DayOfWeek,WatchTV,New Field,_merge
0,Coffee,5,0,8,Sandwich,6,9,2,Tea,2,Long,Mon,Yes,NaN,left_only
1,Doughnut,0,6,2,Lenthils,10,0,1,PingPong,7,Short,Tue,No,NaN,left_only
2,Coffee,3,7,10,Taco,8,4,6,PingPong,2,Short,Wed,No,NaN,left_only
3,Coffee,1,7,3,Sandwich,7,7,8,PingPong,3,Short,Thu,Yes,NaN,left_only
4,Doughnut,5,0,2,Sandwich,5,6,9,Tea,3,Long,Fri,Yes,NaN,left_only
5,Sandwich,8,8,8,Lenthils,3,10,10,Coffee,0,Short,Sat,No,NaN,left_only
6,Doughnut,7,8,1,Lenthils,6,6,4,Coffee,9,Short,Mon,No,NaN,left_only
7,Coffee,7,7,2,Taco,10,7,10,Tea,8,Short,Tue,No,NaN,left_only
8,Sandwich,2,2,8,Lenthils,8,8,0,PingPong,10,Short,Wed,No,NaN,left_only
9,Coffee,6,9,1,Taco,8,8,4,Workout,4,Short,Thu,Yes,NaN,left_only
10,Doughnut,0,2,10,Sandwich,10,1,2,Workout,6,Long,Fri,Yes,NaN,left_only
11,Sandwich,9,8,6,Sandwich,2,9,3,Workout,1,Long,Sat,Yes,NaN,left_only
12,Sandwich,10,7,7,Taco,8,2,6,PingPong,0,Short,Mon,No,NaN,left_only
13,Doughnut,1,10,1,Sandwich,9,5,3,Tea,10,Short,Tue,Yes,NaN,left_only
14,Coffee,7,8,3,Taco,4,7,2,Coffee,5,Short,Wed,Yes,NaN,left_only
15,Coffee,6,10,0,Lenthils,7,5,4,PingPong,8,Short,Thu,No,NaN,left_only
16,Sandwich,4,5,5,Sandwich,1,0,3,PingPong,8,Short,Fri,Yes,NaN,left_only
17,Doughnut,3,5,9,Taco,7,2,6,Coffee,10,Long,Sat,Yes,NaN,left_only
18,Coffee,1,10,7,Taco,6,8,6,Workout,0,Short,Mon,No,NaN,left_only
19,Coffee,0,2,0,Sandwich,8,6,3,Workout,5,Short,Tue,NaN,NaN,left_only
20,Coffee,1,10,4,Lenthils,0,1,7,PingPong,1,Long,Wed,NaN,NaN,left_only

In [112]:
# rows present only in table
result = dataframe_difference(dfx,dft,'right_only')
display(result)

,8AM,9AM,10AM,11AM,Noon,1PM,2PM,3PM,4PM,5PM,Commute,DayOfWeek,WatchTV,New Field,_merge
21,Coffee,3,0,9,Sandwich,9,8,6,Tea,0,Long,Mon,Yes,Blah,right_only
22,Doughnut,8,3,5,Lenthils,10,0,10,PingPong,7,Short,Tue,No,Blah,right_only
23,Coffee,3,1,2,Taco,5,9,2,PingPong,9,Short,Wed,No,Blah,right_only
24,Coffee,8,0,9,Sandwich,1,10,0,PingPong,4,Short,Thu,Yes,Blah,right_only
25,Doughnut,7,10,10,Sandwich,7,0,5,Tea,0,Long,Fri,Yes,Blah,right_only
26,Sandwich,9,5,7,Lenthils,7,1,7,Coffee,10,Short,Sat,No,Blah,right_only
27,Doughnut,7,1,4,Lenthils,8,10,7,Coffee,2,Short,Mon,No,Blah,right_only
28,Coffee,7,7,5,Taco,6,0,8,Tea,8,Short,Tue,No,Blah,right_only
29,Sandwich,9,2,10,Lenthils,2,7,4,PingPong,8,Short,Wed,No,Blah,right_only
30,Coffee,7,0,5,Taco,5,9,0,Workout,8,Short,Thu,Yes,Blah,right_only
31,Doughnut,10,8,8,Sandwich,6,2,9,Workout,9,Long,Fri,Yes,Blah,right_only
32,Sandwich,2,7,0,Sandwich,1,7,7,Workout,5,Long,Sat,Yes,Blah,right_only
33,Sandwich,7,6,3,Taco,6,8,5,PingPong,6,Short,Mon,No,Blah,right_only
34,Doughnut,5,10,7,Sandwich,8,8,7,Tea,7,Short,Tue,Yes,Blah,right_only
35,Coffee,7,7,7,Taco,7,5,2,Coffee,0,Short,Wed,Yes,Blah,right_only
36,Coffee,3,4,6,Lenthils,2,9,3,PingPong,9,Short,Thu,No,Blah,right_only
37,Sandwich,0,3,5,Sandwich,3,2,5,PingPong,9,Short,Fri,Yes,Blah,right_only
38,Doughnut,1,4,5,Taco,6,2,10,Coffee,4,Long,Sat,Yes,Blah,right_only
39,Coffee,2,2,3,Taco,8,10,0,Workout,1,Short,Mon,No,Blah,right_only
40,Coffee,3,5,9,Sandwich,4,2,7,Workout,2,Short,Tue,None,Blah,right_only
41,Coffee,10,9,9,Lenthils,5,2,7,PingPong,5,Long,Wed,None,Blah,right_only

In [113]:
# rows present in XL & table both
result = dataframe_difference(dfx,dft,'both')
display(result)

Empty DataFrame
Columns: [8AM, 9AM, 10AM, 11AM, Noon, 1PM, 2PM, 3PM, 4PM, 5PM, Commute, DayOfWeek, WatchTV, New Field, _merge]
Index: []

#--- only header is displayed as there are no common rows

In [114]:
# identifying additional columns 
result = dataframe_difference(dfx,dft)
display(result)

# dft=dft.drop(['index','New Field'], axis=1)

sql_conn.close()

,8AM,9AM,10AM,11AM,Noon,1PM,2PM,3PM,4PM,5PM,Commute,DayOfWeek,WatchTV,New Field,_merge
0,Coffee,5,0,8,Sandwich,6,9,2,Tea,2,Long,Mon,Yes,NaN,left_only
1,Doughnut,0,6,2,Lenthils,10,0,1,PingPong,7,Short,Tue,No,NaN,left_only
2,Coffee,3,7,10,Taco,8,4,6,PingPong,2,Short,Wed,No,NaN,left_only
3,Coffee,1,7,3,Sandwich,7,7,8,PingPong,3,Short,Thu,Yes,NaN,left_only
4,Doughnut,5,0,2,Sandwich,5,6,9,Tea,3,Long,Fri,Yes,NaN,left_only
5,Sandwich,8,8,8,Lenthils,3,10,10,Coffee,0,Short,Sat,No,NaN,left_only
6,Doughnut,7,8,1,Lenthils,6,6,4,Coffee,9,Short,Mon,No,NaN,left_only
7,Coffee,7,7,2,Taco,10,7,10,Tea,8,Short,Tue,No,NaN,left_only
8,Sandwich,2,2,8,Lenthils,8,8,0,PingPong,10,Short,Wed,No,NaN,left_only
9,Coffee,6,9,1,Taco,8,8,4,Workout,4,Short,Thu,Yes,NaN,left_only
10,Doughnut,0,2,10,Sandwich,10,1,2,Workout,6,Long,Fri,Yes,NaN,left_only
11,Sandwich,9,8,6,Sandwich,2,9,3,Workout,1,Long,Sat,Yes,NaN,left_only
12,Sandwich,10,7,7,Taco,8,2,6,PingPong,0,Short,Mon,No,NaN,left_only
13,Doughnut,1,10,1,Sandwich,9,5,3,Tea,10,Short,Tue,Yes,NaN,left_only
14,Coffee,7,8,3,Taco,4,7,2,Coffee,5,Short,Wed,Yes,NaN,left_only
15,Coffee,6,10,0,Lenthils,7,5,4,PingPong,8,Short,Thu,No,NaN,left_only
16,Sandwich,4,5,5,Sandwich,1,0,3,PingPong,8,Short,Fri,Yes,NaN,left_only
17,Doughnut,3,5,9,Taco,7,2,6,Coffee,10,Long,Sat,Yes,NaN,left_only
18,Coffee,1,10,7,Taco,6,8,6,Workout,0,Short,Mon,No,NaN,left_only
19,Coffee,0,2,0,Sandwich,8,6,3,Workout,5,Short,Tue,NaN,NaN,left_only
20,Coffee,1,10,4,Lenthils,0,1,7,PingPong,1,Long,Wed,NaN,NaN,left_only
21,Coffee,3,0,9,Sandwich,9,8,6,Tea,0,Long,Mon,Yes,Blah,right_only
22,Doughnut,8,3,5,Lenthils,10,0,10,PingPong,7,Short,Tue,No,Blah,right_only
23,Coffee,3,1,2,Taco,5,9,2,PingPong,9,Short,Wed,No,Blah,right_only
24,Coffee,8,0,9,Sandwich,1,10,0,PingPong,4,Short,Thu,Yes,Blah,right_only
25,Doughnut,7,10,10,Sandwich,7,0,5,Tea,0,Long,Fri,Yes,Blah,right_only
26,Sandwich,9,5,7,Lenthils,7,1,7,Coffee,10,Short,Sat,No,Blah,right_only
27,Doughnut,7,1,4,Lenthils,8,10,7,Coffee,2,Short,Mon,No,Blah,right_only
28,Coffee,7,7,5,Taco,6,0,8,Tea,8,Short,Tue,No,Blah,right_only
29,Sandwich,9,2,10,Lenthils,2,7,4,PingPong,8,Short,Wed,No,Blah,right_only
30,Coffee,7,0,5,Taco,5,9,0,Workout,8,Short,Thu,Yes,Blah,right_only
31,Doughnut,10,8,8,Sandwich,6,2,9,Workout,9,Long,Fri,Yes,Blah,right_only
32,Sandwich,2,7,0,Sandwich,1,7,7,Workout,5,Long,Sat,Yes,Blah,right_only
33,Sandwich,7,6,3,Taco,6,8,5,PingPong,6,Short,Mon,No,Blah,right_only
34,Doughnut,5,10,7,Sandwich,8,8,7,Tea,7,Short,Tue,Yes,Blah,right_only
35,Coffee,7,7,7,Taco,7,5,2,Coffee,0,Short,Wed,Yes,Blah,right_only
36,Coffee,3,4,6,Lenthils,2,9,3,PingPong,9,Short,Thu,No,Blah,right_only
37,Sandwich,0,3,5,Sandwich,3,2,5,PingPong,9,Short,Fri,Yes,Blah,right_only
38,Doughnut,1,4,5,Taco,6,2,10,Coffee,4,Long,Sat,Yes,Blah,right_only
39,Coffee,2,2,3,Taco,8,10,0,Workout,1,Short,Mon,No,Blah,right_only
40,Coffee,3,5,9,Sandwich,4,2,7,Workout,2,Short,Tue,None,Blah,right_only
41,Coffee,10,9,9,Lenthils,5,2,7,PingPong,5,Long,Wed,None,Blah,right_only